version: '3.7'

services:
  web_cv:
    container_name: bruno-sautron-io-cv
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - proxy-conf:/app/nginx/conf/:rw
      - proxy-static:/app/:rw

volumes:
  proxy-conf:
    external: true
  proxy-static:
    external: true

